### ISSUE TITLE
Improve UI to support searching/filtering/sorting 

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/pleuston#137]
* Part of https://github.com/oceanprotocol/ocean/issues/13
* Implemented in https://github.com/oceanprotocol/pleuston/pull/133

**Comment by JohnBDB** [comment]
@kremalicious @JohnBDB to work on description for this issue

**Comment by kremalicious** [comment]
A first iteration for search and basic filtering has been included in #133
