### ISSUE TITLE
Missing information about token variable for codacy-coverage

### ISSUE THREAD

**Issue by jjperezaguinaga** [oceanprotocol/pleuston#160]
See #159 for all the issue template requirements.

In short, the project requires a token for `codacy-coverage` that it's not described in the Documentation. Thus, it fails when the user tries to run `npm run test` locally, as well as within a request from a non-contributor.

Let's update the Documentation to include some Steps on How To add the token for at least allowing people to be aware of this, or create a conditional to change this command on Travis only.

**Comment by ttmc** [comment]
Note: This is also an issue with Aquarius and all other repos that use `codacy-coverage` in Travis.
