### ISSUE TITLE
can't register assets

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/pleuston#162]
When hitting Publish with all the `--latest` components, the transaction goes through successfully, but the response returns a 404, making registering any asset fail:

<img width="858" alt="screen shot 2018-11-05 at 12 41 18" src="https://user-images.githubusercontent.com/90316/47996294-5eb17700-e0f8-11e8-8e87-7e408bfd3c7e.png">

Looks like the asset ID is just `null` for whatever reason.

## Steps to Reproduce the problem

1. Go to `/publish`
2. Enter required data, hit publish
3. Confirm the transaction with MetaMask
4. After transaction ran through successfully, inspect the console

### Possible Solution

Might be `Aquarius` related and if something changed there we need to update register flow in `Pleuston`

**Comment by eruizgar91** [comment]
This is because we split the provider into two components:
- Aquarius -> In charge exclusively of the metadata.
- Brizo -> In charge of the consume, compute endpoints and further to come.
We are currently working in get the first docker-image of brizo and we will change it in the docker-images repo as well.
I assume that the change that is required in pleuston is just point for purchase to the brizo url that we are going to use in local as `localhost:8030`.

**Comment by jernejpregelj** [comment]
Updating the state on this issue:
- using squd-js 0.1.7
- docker-images with --latest

logs:
![screenshot 2018-11-09 at 09 57 01](https://user-images.githubusercontent.com/7147341/48252965-70e82980-e406-11e8-9395-2f6326c1bdc3.png)

request object from from network:
<img width="942" alt="screenshot 2018-11-09 at 09 56 48" src="https://user-images.githubusercontent.com/7147341/48252987-80677280-e406-11e8-8621-6b3d5a64f1c5.png">

**Comment by jernejpregelj** [comment]
Update on issue:

Secret store POST request does not fullfill conditions for triggering CORS preflight see details: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

**Comment by kremalicious** [comment]
Also testing this again against the links PR #151 with latest changes merged in. Using also latest docker-images with `--latest --no-pleuston`. I still get the originally mentioned 404 message

**Comment by jernejpregelj** [comment]
Publishing works now on #133
