### ISSUE TITLE
The "make it rain" button only sends 0.00000000000000001 tokens

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/pleuston#186]
This issue was [reported by @imthatcarlos in Gitter](https://gitter.im/oceanprotocol/Lobby?at=5c98ea36a21ce51a20bbf8c3).

It seems there is an error in units, e.g. "I asked for one Ocean token but I got one Vodka."

**Comment by kremalicious** [comment]
Functionality was removed in #188
