### ISSUE TITLE
metadata response is weirdly escaped

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/pleuston#37]
Doesn't cause any issue except for development tools not being able to show it properly which is a pain for debugging.

<img width="926" alt="screen shot 2018-08-16 at 13 59 16" src="https://user-images.githubusercontent.com/90316/44207193-985b8d00-a15c-11e8-915f-10168792a021.png">

**Comment by H34D** [comment]
looks like a bad usage of json serializer

**Comment by ssallam** [comment]
Can't reproduce.

**Comment by kremalicious** [comment]
in Chrome dev tools:

<img width="1338" alt="screen shot 2018-08-21 at 16 09 48" src="https://user-images.githubusercontent.com/90316/44406751-b100e400-a55c-11e8-8fd4-817e2236825e.png">
